env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  {
    "no-use-before-define": "off",
    "react/jsx-filename-extension": [1, { extensions: [".tsx"] }],
  }
