version: "3.9"
services:
  blog-backend-api:
    build: backend/blog
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend/blog:/app
  web-frontend:
    build: frontend/web
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
