swagger: '2.0'
info:
  title: api.tocoteron.com
  description: ""
  termsOfService: ""
  contact:
    name: tocoteron
    email: tocoteorn@gmail.com
  license:
    name: ""
  version: '1.0.0'
host: api.tocoteorn.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /posts:
    get:
      tags:
      - Blog
      summary: "Get all posts"
      description: "Get all posts"
      responses:
        '200':
          description: All posts
          schema:
            type: array
            items:
              $ref: '#/definitions/BlogPost'
  /posts/{id}:
    get:
      tags:
      - Blog
      summary: "Get a post"
      description: "Get a post"
      parameters:
      - name: id
        in: path
        description: "ID of a post"
        required: true
        type: integer
        format: int64
      responses:
        '200':
          description: All posts
          schema:
            type: object
            $ref: '#/definitions/BlogPost'
definitions:
  BlogPost:
    type: object
    properties:
      id:
        type: integer
        format: int64
      content:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
